services:
  app:
    image: acme/service-article:dev
    container_name: service-article
    environment:
      QUARKUS_PROFILE: docker
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/service_article
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
