apiVersion: v1
kind: Secret
metadata:
  name: article-service-secrets
  namespace: production
type: Opaque
stringData:
  # Identifiants de la base de donn√©es
  # Remplacez par vos vrais identifiants
  db.username: "article_user"
  db.password: "secure_password_123"
