apiVersion: v1
    protocol: TCP
    targetPort: 8080
    port: 80
  - name: http
  ports:
    app: article-service
  selector:
  type: ClusterIP
spec:
    app: article-service
  labels:
  name: article-service
metadata:
kind: Service

