apiVersion: v1
kind: Service
metadata:
  name: article-service
  labels:
    app: article-service
spec:
  type: ClusterIP
  selector:
    app: article-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
